params:
- name: AAO
  enabled: false
  order: 10
- name: ANN
  enabled: false
  order: 6
- name: ARCHDIST
  enabled: true
  order: 1
- name: ARCHPROX
  enabled: true
  order: 40
- name: ISTH
  enabled: true
  order: 50
- name: LAD
  enabled: true
  order: 2
- name: LMCA
  enabled: false
  order: 70
- name: LPA
  enabled: false
  order: 80
- name: LVEDA
  enabled: false
  order: 90
- name: LVEDAEPI
  enabled: false
  order: 100
- name: LVEDD
  enabled: false
  order: 10
- name: LVEDL
  enabled: false
  order: 120
- name: LVEDLEPI
  enabled: false
  order: 130
- name: LVEDV
  enabled: false
  order: 140
- name: LVEDVEPI
  enabled: false
  order: 150
- name: LVM
  enabled: false
  order: 160
- name: LVMTV
  enabled: false
  order: 170
- name: LVPWT
  enabled: false
  order: 180
- name: LVSI
  enabled: false
  order: 999
- name: LVST
  enabled: false
  order: 200
- name: LVTTD
  enabled: false
  order: 210
- name: MPA
  enabled: false
  order: 220
- name: MVA
  enabled: false
  order: 230
- name: MVAP
  enabled: false
  order: 240
- name: MVLAT
  enabled: false
  order: 250
- name: PVLAX
  enabled: false
  order: 260
- name: PVSAX
  enabled: false
  order: 270
- name: RCA
  enabled: false
  order: 280
- name: ROOT
  enabled: false
  order: 20
- name: RPA
  enabled: false
  order: 300
- name: STJ
  enabled: false
  order: 310
- name: TVA
  enabled: false
  order: 320
- name: TVAP
  enabled: false
  order: 330
- name: TVLAT
  enabled: false
  order: 340
