params:
- name: AAO
  enabled: true
  order: 70
- name: ANN
  enabled: true
  order: 40
- name: ARCHDIST
  enabled: false
  order: 9999
- name: ARCHPROX
  enabled: false
  order: 9999
- name: ISTH
  enabled: false
  order: 9999
- name: LAD
  enabled: false
  order: 9999
- name: LMCA
  enabled: false
  order: 9999
- name: LPA
  enabled: true
  order: 100
- name: LVEDA
  enabled: false
  order: 9999
- name: LVEDAEPI
  enabled: false
  order: 9999
- name: LVEDD
  enabled: true
  order: 10
- name: LVEDL
  enabled: false
  order: 9999
- name: LVEDLEPI
  enabled: false
  order: 9999
- name: LVEDV
  enabled: false
  order: 9999
- name: LVEDVEPI
  enabled: false
  order: 9999
- name: LVM
  enabled: false
  order: 9999
- name: LVMTV
  enabled: false
  order: 9999
- name: LVPWT
  enabled: true
  order: 30
- name: LVSI
  enabled: false
  order: 9999
- name: LVST
  enabled: true
  order: 20
- name: LVTTD
  enabled: false
  order: 9999
- name: MPA
  enabled: true
  order: 80
- name: MVA
  enabled: false
  order: 9999
- name: MVAP
  enabled: false
  order: 9999
- name: MVLAT
  enabled: false
  order: 9999
- name: PVLAX
  enabled: false
  order: 9999
- name: PVSAX
  enabled: false
  order: 9999
- name: RCA
  enabled: false
  order: 9999
- name: ROOT
  enabled: true
  order: 50
- name: RPA
  enabled: true
  order: 90
- name: STJ
  enabled: true
  order: 60
- name: TVA
  enabled: false
  order: 9999
- name: TVAP
  enabled: false
  order: 9999
- name: TVLAT
  enabled: false
  order: 9999
